name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
      env:
        CI: true

    - name: Build application
      run: npm run build -- --configuration production

  docker-build-and-push:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  notify:
    needs: docker-build-and-push
    if: always()
    runs-on: ubuntu-latest
    
    steps:
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.tjekgamer@mail.ru }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: ${{ job.status }}: CI/CD Pipeline for ${{ github.repository }}
        to: your-email@example.com
        from: GitHub Actions
        body: |
          Pipeline status: ${{ job.status }}
          Repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Workflow: ${{ github.workflow }}
          View details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        html_body: |
          <h2>CI/CD Pipeline Status: ${{ job.status }}</h2>
          <p><strong>Repository:</strong> ${{ github.repository }}</p>
          <p><strong>Commit:</strong> ${{ github.sha }}</p>
          <p><strong>Workflow:</strong> ${{ github.workflow }}</p>
          <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View details</a></p>
